### ISSUE TITLE
反馈2个问题

### ISSUE THREAD

**Issue by easydowork** [krissss/yii2-wang-editor#1]
1，UploadAction getFileName方法报错。
$filename = md5(microtime() + random_int(10000, 99999));
建议+号改成.
2，加一个本地文件上传到后服务器后 在run 的 returnSuccess 之前可以写个 before 事件 留个服务器上传到第三方存储的方法。

**Comment by krissss** [comment]
第一个问题fixed

第二个问题可以通过 `saveFileCallback` 参数解决

**Comment by easydowork** [comment]
saveFileCallback 虽然可以上传到第三方,返回第三方图片地址有点问题。 displayPath 好像并不能改成 url的格式

**Comment by krissss** [comment]
displayPath 设置为 `http://域名` 的形式就行了

**Comment by easydowork** [comment]
displayPath 设置为 http://域名 + 路径好像会报错  例如 http://www.test.com/upload/images

**Comment by krissss** [comment]
麻烦把你的代码发一下
