### ISSUE TITLE
关于表单无法验证的问题

### ISSUE THREAD

**Issue by InfoButler-LinaLu** [krissss/yii2-wang-editor#2]
在1.0中，可以配置js，如下：
` {name}.customConfig.uploadImgServer = '$uploadUrl';
    {name}.customConfig.zIndex = 99;
    {name}.customConfig.uploadImgParams = {
    '_csrf-backend': '$_csrf'
};`
但在2.0中无法配置uploadImgParams 字段，造成表单提交验证错误，报如下错误：

> yii\web\BadRequestHttpException: Unable to verify your data submission. in /Applications/XAMPP/xamppfiles/htdocs/MT/vendor/yiisoft/yii2/web/Controller.php:187
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/MT/vendor/yiisoft/yii2/base/Controller.php(155): yii\web\Controller->beforeAction(Object(yii\base\InlineAction))
#1 /Applications/XAMPP/xamppfiles/htdocs/MT/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('upload-img', Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/MT/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('post/upload-img', Array)
#3 /Applications/XAMPP/xamppfiles/htdocs/MT/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#4 /Applications/XAMPP/xamppfiles/htdocs/MT/backend/web/index.php(17): yii\base\Application->run()
#5 {main}

请问有没有什么办法能够将验证字段配置进去？

**Comment by krissss** [comment]
`widget` 下的配置参数 `customConfig`

```php
WangEditorWidget::widget([
    // 其他
    'customConfig' => [
        'uploadImgParams' => ['_csrf-backend': $_csrf]
    ],
]);
```

**Comment by InfoButler-LinaLu** [comment]
已经成功提交图片，能不能将这个验证项做到widget的文件内？如果每次升级都需要手工配置非常不方便，不知道能不能在代码中直接包含验证字段？

但是按照示例的上传action配置，获得以下报错：

> yii\base\InvalidArgumentException: Response content must not be an array. in /Applications/XAMPP/xamppfiles/htdocs/MT/vendor/yiisoft/yii2/web/Response.php:1082
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/MT/vendor/yiisoft/yii2/web/Response.php(337): yii\web\Response->prepare()
#1 /Applications/XAMPP/xamppfiles/htdocs/MT/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Response->send()
#2 /Applications/XAMPP/xamppfiles/htdocs/MT/backend/web/index.php(17): yii\base\Application->run()
#3 {main}

按照官方文档

>   // 如果服务器端返回的不是 {errno:0, data: [...]} 这种格式，可使用该配置
    // （但是，服务器端返回的必须是一个 JSON 格式字符串！！！否则会报错）

需要回调一个json，但示例中返回的是数组。 进行json_encode后，图片上传依然失败，并且图片并没有上传到服务器指定位置

**Comment by krissss** [comment]
1. csrf的token参数是可以自定义的（或者可以禁用），不一定叫`_csrf-backend`，所以该参数只能通过这种形式定义，再比如说万一再需要上传更多的额外参数呢，那是不是要配置更多参数到widget里了。。。
2. 若是你项目下固定需要这个参数，你可以通过继承实现，然后使用你自己的widget（或者直接使用contianer下的defination配置统一替换）
3. 报 `Response content must not be an array`一定是你的action存在问题，[此处代码](https://github.com/krissss/yii2-wang-editor/blob/d577c35f6f503b4919a6db6a1fcfd5b5d1d24c59/src/actions/BaseAction.php#L35)已经将返回格式改为json
4. [此处代码](https://github.com/krissss/yii2-wang-editor/blob/d577c35f6f503b4919a6db6a1fcfd5b5d1d24c59/src/actions/BaseAction.php#L36)其实已经将csrf校验关闭，那么你之前出现csrf校验问题，只能说你用的action不是最新的这个

**Comment by krissss** [comment]
我想我大概知道你报 `Response content must not be an array` 的原因了，你是不是写的

```php
public function actionUploadImg()
    {
        return [
            'wang-editor' => [
                'class' => UploadAction::class,
                'savePath' => '@webroot/uploads',
                'displayPath' => '@web/uploads',
            ],
        ];
    }
```

请注意示例中是 `actions`，而不是 `actionUploadImg`

这一点你需要关注文档，了解一下什么是 StandaloneAction，[文档](https://www.yiiframework.com/doc/guide/2.0/en/structure-controllers#standalone-actions)
